### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by JohnCoene** [tliron/kutil#2]
Thank you for this! I used it as part of your [glsp](https://github.com/tliron/glsp) package.

When trying to build for windows I get the following error

```bash
$ env GOOS=windows GOARCH=amd64 go build
# github.com/tliron/kutil/terminal
/home/john/go/bin/pkg/mod/github.com/tliron/kutil@v0.3.11/terminal/color_enable_windows.go:18:26: output.EnableWindowsANSIConsole undefined (type *termenv.Output has no field or method EnableWindowsANSIConsole)
/home/john/go/bin/pkg/mod/github.com/tliron/kutil@v0.3.11/terminal/color_enable_windows.go:20:19: output.RestoreWindowsConsole undefined (type *termenv.Output has no field or method RestoreWindowsConsole)
```

**Comment by tliron** [comment]
Thanks for opening issue. This is a regression, I thought I had fixed this. :/

**Comment by tliron** [comment]
OK, so it was fixed a while ago, but GLSP may have still been using an older version via an indirect dependency, commonlog. I have updated everything. Can you check with with the latest commit of GLSP to see if it works for you?

**Comment by JohnCoene** [comment]
It works like a charm now, thank you!
